### ISSUE TITLE
Fix the memory leak in get TH2D from SIM 

### ISSUE THREAD

**Issue by emanueledimarco** [CYGNUS-RD/reconstruction#215]
The retrieval of TH2D saved in the ROOT files, now done with [uproot](https://uproot.readthedocs.io/en/latest/index.html), instead of root_numpy, seems to leak (removing all the code apart the loop over events and TH2 get, one can notice a large increase of memory).
If this is related to uproot, it needs to be followed up with uproot developers

**Comment by emanueledimarco** [comment]
@gdimperi

**Comment by GioDho** [comment]
Solved by PR 261
