### ISSUE TITLE
Reconstruction error while using .root files or .mid from before Run3

### ISSUE THREAD

**Issue by ifpains** [CYGNUS-RD/reconstruction#222]
- The latest PR (#221) added a few lines on the reconstruction.py that do not work properly for .root files or .mid from before Run3. Some ifs probably need to be added to avoid those errors. 
- The image rotation of .mid files was inverted again on the latest PR (check #217 where I fixed that). Needs to be changed back to the way it was before #221.

**Comment by emanueledimarco** [comment]
@antorita could you fix this and propose a pull request? Also, I didn't tested on Run2 data, but we need to ensure backward compatibility (as @ifpains says, some if on the run-range should be sufficient, better if triggered in configuration file, or dynamically - checking the existence of the new variables)

@igorabritta @davidepinci

**Comment by emanueledimarco** [comment]
@antorita it should revert the rotation of the pedestal back to PR #217 (check the diffs with that version). Thanks!

**Comment by emanueledimarco** [comment]
I merged PR #223 without testing it on Run2 / Run3 data. Let's check it before closing the issue.

**Comment by antorita** [comment]
I tested the reconstruction on some run belonging on run1/run2/run3, in particular:
2000
5000
12000
12151
17500
17501
19500
19501

**Comment by emanueledimarco** [comment]
OK thanks a lot @antorita . Closing the issue then 

@ifpains @igorabritta
